apiVersion: app-scanning.apps.tanzu.vmware.com/v1alpha1
kind: RecurringImageVulnerabilityScan
metadata:
  name: depscan-recurring-scan
spec:
  images:
    createdWithinDays: 180
    ranWithinDays: 0
  retentionPolicy:
    maxFailedScans: 1
    maxSuccessfulScans: 1
  schedule:
    cron: 0 3 * * *
    startingDeadline: 60m
  scan:
    workspace:
      size: 30Gi
    scanResults:
      location: MY-REG/REPO
    steps:
      - args:
          - -c
          - |
            set -x
            wget https://github.com/carvel-dev/vendir/releases/download/v0.40.0/vendir-linux-amd64
            chmod +x vendir-linux-amd64
            cat <<EOF > $TMPDIR/vendir.yml
            apiVersion: vendir.k14s.io/v1alpha1
            kind: Config
            directories:
            - path: vendor
              contents:
              - path: .
                image:
                  url: "{image}"
            EOF
            ./vendir-linux-amd64 sync --chdir $TMPDIR
        command:
          - /bin/sh
        image: index.docker.io/library/alpine@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
        name: extract
      - image: ghcr.io/owasp-dep-scan/dep-scan@sha256:09636ab4974929d524457e4f47ab161c8f660ea871a356e93e7fb7090b592cac
        name: depscan
        args: [ --debug, --src, /workspace/tmp/vendor, --reports-dir, "{output}" ]
        env:
          - name: VDB_HOME
            value: /workspace/vdb
      - args:
          - -c
          - |
            set -x
            ls {output}
            rm {output}/depscan*
            rm {output}/sbom-universal.json
            mv {output}/*.vdr.json {output}/scan.cdx.json
            ls {output}
        command:
          - /bin/sh
        image: index.docker.io/library/alpine@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
        name: cleanup